### ISSUE TITLE
Set up Lighthouse CI

### ISSUE THREAD

**Issue by jsjoeio** [jsjoeio/joeprevite.com#41]
**Describe the bug**
Currently, when you open a PR, the CI fails on the first run. This is because the GH action runs before the Netlify deploy is ready.

**To Reproduce**

1. Open a PR
2. Watch the GitHub Checks/CI run
3. See error

**Expected behavior**
The CI should run after the deploy preview is ready.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jsjoeio** [comment]
Ideal solution: [run action on deploy/status event](https://twitter.com/kuldeepkeshwar/status/1213906550336548864?s=20) suggested by @kuldeepkeshwar

Backup solution: [Deploy to Netlify from Action](https://twitter.com/kevinwolfcr/status/1213914037668515840?s=20) suggested by @iamkevinwolf

**Comment by jsjoeio** [comment]
@JakePartusch also wrote a GH Action to help solve this issue called [`wait-for-netlify-action`](https://github.com/JakePartusch/wait-for-netlify-action)

**Comment by kvnwolf** [comment]
> @JakePartusch also wrote a GH Action to help solve this issue called [`wait-for-netlify-action`](https://github.com/JakePartusch/wait-for-netlify-action)

Nice one! How did it come with the "run action on deploy/status event" approach?

**Comment by jsjoeio** [comment]
I haven't tackled this yet! I will maybe later this week or weekend. I'll let you know how it goes!

**Comment by JakePartusch** [comment]
👋 Here's the link to action: https://github.com/JakePartusch/wait-for-netlify-action

It doesn't do anything fancy, just keeps pinging the preview url every few seconds until it gets a 200 or the timeout is reached.

Example of the action in "action" https://github.com/JakePartusch/website/commit/04f342137dc8d6b1256cf616e283d99a5fe7b6ef/checks?check_suite_id=386932234

**Comment by jsjoeio** [comment]
Fantastic! Thanks for adding that example too @JakePartusch 🙏

Sidenote: I wish there were a way for that Lighthouse action to leave a comment on the PR with the table of scores (instead of us having to look at the GH action logs 😅 ) but I guess that's a problem for another day 😂

**Comment by JakePartusch** [comment]
You can sort of do that with https://github.com/GoogleChrome/lighthouse-ci

<img width="752" alt="Screen Shot 2020-01-06 at 3 40 36 PM" src="https://user-images.githubusercontent.com/6424140/71850879-e72ffc80-309a-11ea-9a5c-c5652eac01f8.png">

The LHCI_GITHUB_APP_TOKEN is the secret sauce:
```
      - name: Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitFor200.outputs.url }} || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
```
https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-app-method-recommended

**Comment by jsjoeio** [comment]
Oh perfect! You're the man. Thanks @JakePartusch ! 🙌

**Comment by jsjoeio** [comment]
Let's hope #44 solved this! Going to open a PR to test.

**Comment by jsjoeio** [comment]
Sadly, I don't think running the action on the status event is working as expected 😢

You can see in #46. ~I think I'm going to try the lighthouse-ci instead.~

Actually, after looking at the docs for all solutions, I feel like @JakePartusch your `wait-for-netlify` is the simplest/most straightforward. Going to try that instead.

**Comment by jsjoeio** [comment]
It worked!!! 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/3806031/71898515-bd1c2000-3116-11ea-85bc-3feb7a614c40.png">

**Comment by jsjoeio** [comment]
Woo! I ended up getting it to work. Here's the workflow:

```yaml
name: Test Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: 'keen-roentgen-cafcb7'
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          author: ${{ github.actor }}
          branch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          urls: 'https://deploy-preview-${{ github.event.pull_request.number }}--keen-roentgen-cafcb7.netlify.com'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
```
